esphome:
    name: hpsu-can
    friendly_name: HPSU.CAN
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://Trunks1982/Daikin-Rotex-HPSU-CAN

#
#external_components:   # Use this block instead of the one above if you want to use the development branch
#  - source:
#      type: git
#      url: https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN.git
#      ref: dev
#    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

button:
  - platform: restart
    name: "Rotex ESP Restart"
#switch:
#  - platform: gpio
#    name: Smart Grid
#    pin:
#      number: GPIO06
#      inverted: true

#  - platform: gpio
#    name: EVU
#    pin:
#      number: GPIO05
#      inverted: true

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO5
    rx_pin: GPIO6
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  canbus_id: can_bus
  # tranlation language, supported: de, en, it. If not set, the default language is de
  language: de
  update_interval: 30
  #max_spread_tvbh_tv: 4
  #max_spread_tvbh_tr: 4
  log_filter:
    name: Log Filter
  custom_request:
    name: Custom Request
  dump:
    name: Dump Senors
  project_git_hash:
    name: Project Git Hash

entities:

# Info

#mode
    ext:
      name: auto
#RT
#Pump
#EHS
#BPV
    tv:
      name: auto
      update_interval: 5
    tvbh:
      name: auto
      update_interval: 5
    tr:
      name: auto
      update_interval: 5
#Tdhw
    temperature_outside:  # ta
      name: auto
#V
#TVBH2
#TR2
#Tdhw2
    tliq:
      name: auto # if set to auto, the name will be translated from dictionary in the specified language
    ta2:
      name: auto
#quiet

#Übersicht
    water_pressure:
      name: auto
    t_hs:
      name: auto
#T-WE Soll
    t_ext:  # Oder gehört hier temperature_outside rein?
      name: auto
#T-WW
#T-WW Soll
#T-Rücklauf
    flow_rate:
      name: auto
      update_interval: 10
#T-HK
#T-HK Soll
    status_kesselpumpe:
      name: auto
    runtime_compressor:
      name: auto
    runtime_pump:
      name: auto
    dhw_mixer_position:
      name: auto
    qboh:
      name: auto
    ehs_for_ch:
      name: auto
    energy_cooling:
      name: auto
    qch:
      name: auto
    total_energy_produced:
      name: auto
    qdhw:
      name: auto
    total_electrical_energy:
      name: auto
#WE Typ
#SwNr B1/U1
#SwNr Regler
#SwNr RTXRT

# ESP custom sensors
    energy_saving_mode:
      name: auto

# Betriebsart
    operating_mode:
      name: auto
      update_interval: 5

# Raum Soll Tag
    target_room1_temperature:
      name: auto
      type: select
  # T-RaumSoll 2
  # T-RaumSoll 3

# Raum Soll Nacht
  # T-Absenkung
  # T-Abwesend

# WW Solltemp
    target_hot_water_temperature:
      name: auto
      type: select

  # T-WWSoll 2
  # T-WWSoll 3

# WW Install
    1_dhw:
      name: auto
    hp_hyst_tdhw:
      name: auto
    delay_time_for_backup_heating:
      name: auto

#Konfiguration

#Konfiguration -> Installation
#...
    outdoor_unit:
      name: auto
    indoor_unit:
      name: auto
    function_ehs:
      name: auto
    ch_support:
      name: auto
#Bivalenzfunktion
    smart_grid:
      name: auto
    sg_mode:
      name: auto
#HT/NT Funktion
#HT/NT Anschluss
#Raumthermostat
#Interlinkfunktion
#Konfig MFR 1
#Entlüftungsfunktion
#PWM Konfig
#...
#Sensor Konfig
    external_temp_sensor:
      name: auto
    # SKonfig T-WW
    # SKonfig Druck
#AF Anspassung
#Terminal Adresse
#Konfig System

#Konfiguration -> Anlagenkonfiguration

    power_dhw:
      name: auto
      #type: select
    power_ehs_1:
      name: auto
    power_ehs_2:
      name: auto
    power_biv:
      name: auto
    tdiff_dhw_ch:
      name: auto
    max_heating_temperature:
      name: auto
    quiet:
      name: auto
#Sonderfunkt Schaltk
#Wartezeit Sonderfunkt
    t_dhw_1_min:
      name: auto
    delta_temp_ch:
      name: auto
    delta_temp_dhw:           # service
      name: auto
#VerzZeitPumpe                # service
    flow_rate_min:            # service
      name: auto
    flow_rate_setpoint:       # service
      name: auto
    flow_rate_calc:           # service
      name: auto
    flow_rate_hyst:           # service
      name: auto
    supply_temperature_adjustment_heating:
      name: auto
    supply_temperature_adjustment_cooling:
      name: auto
#Min Druck
#Max Druck
#Soll Druck
#Max Druckverlust
#Relaistest

# Konfiguration -> HZK Konfig
    hk_function:
      name: auto
    temperature_antifreeze:
      name: auto
#Gebäudedämumng
#Estrich
#Estrichprogramm

# Konfiguration -> HZK Konfig -> Heizen

    heating_limit_day:
      name: auto
    heating_limit_night:
      name: auto
    heating_curve:
      name: auto
#Raumeinfluss
#RF Anpassung
    flow_temperature_day:
      name: auto
    flow_temperature_night:
      name: auto
    max_target_flow_temp:
      name: auto
    min_target_flow_temp:
      name: auto
#Heizk Adaption

# Konfiguration -> HZK Konfig -> Kühlen

#StartKühlen A-Temp
#MaxKühlen A-Temp
#VL-SollStartKühlen
#VL-SollMaxKühlen
#MinVL-SollKühlen
#T-VLKühlen
#T_H/K Umschaltung
#KühlsollwertKorr

#Konfiguration -> WW Konfig

    circulation_with_dhw_program:
      name: auto
    circulation_interval_on:
      name: auto
    circulation_interval_off:
      name: auto
    antileg_day:
      name: auto
    antileg_temp:
      name: auto
    max_dhw_loading:
      name: auto
    dhw_off_time:
      name: auto

# Others

    electric_heater:
      name: auto
    thermal_power:
      name: auto
    optimized_defrosting:
      name: auto

# To be categorized

    bypass_valve:
      name: auto
    circulation_pump:
      name: auto
    circulation_pump_min:
      name: auto
    circulation_pump_max:
      name: auto
    dhw_run:
      name: auto
    error_code:
      name: auto
    mode_of_operating:
      name: auto
    status_kompressor:
      name: auto
    tdhw1:
      name: auto
    target_supply_temperature:
      name: auto
